{{- if .Values.serviceAccount.create -}}
{{- if .Values.clusterScoped }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
subjects:
    - kind: ServiceAccount
      name: {{ include "chart.fullname" . }}
roleRef:
  {{- if .Values.clusterScoped }}
    kind: ClusterRole
  {{- else }}
    kind: Role
  {{- end }}
    name: {{ include "chart.fullname" . }}
    apiGroup: rbac.authorization.k8s.io
{{- end -}}